<?php

namespace UCI\Boson\EyCBundle\Entity;

use Doctrine\ORM\EntityRepository;
use UCI\Boson\EyCBundle\Entity\CampoNom;
use Doctrine\ORM\NoResultException;


/**
 * CampoNomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampoNomRepository extends EntityRepository
{

}
