<?php

namespace UCI\Boson\EyCBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CampoEstrucRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampoEstrucRepository extends EntityRepository
{
}
