<?php

namespace UCI\Boson\EyCBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Doctrine\ORM\Query;

/**
 * NomencladorOpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorOpRepository extends EntityRepository
{
    public function findByMostrarValoresCamposNomOp($idn, $order, $page, $limit, $filter,$cantCampos,$direction)
    {
        $em = $this->getEntityManager();

        $dql = 'SELECT nop.id as IDNOP,nop.nombre as NomNOP, cn.nombre as nombrecampo, vn.id, vn.valor
                  FROM EyCBundle:ValoresNom vn
                  JOIN vn.campoNom cn
                  JOIN vn.nomencladorOp nop
                  JOIN nop.nomenclador no
                 WHERE no.id = :idn
                 ORDER BY nop.id,vn.id ASC';
//        AND vn.valor LIKE \'%'.$filter.'%\'
        $respuesta = array();
        $consulta = $em->createQuery($dql);
        $consulta->setFirstResult(($page - 1) * $limit*$cantCampos)
            ->setMaxResults($limit*$cantCampos);
        $consulta->setParameter('idn', $idn);

        $arreglar = $consulta->getArrayResult();
        $ids = array();
        for($i = 0; $i < count($arreglar); $i++){
            if(!in_array($arreglar[$i]['IDNOP'],$ids)){
                array_push($ids,$arreglar[$i]['IDNOP']);
            }
        }
//        print_r($ids);
//        exit();

        $valores = array();
        for($i = 0; $i < count($ids); $i++){
            $ins = array();
            $nomb = '';
            for($j = 0; $j < count($arreglar); $j++){
                                if($arreglar[$j]['IDNOP'] == $ids[$i]){
                    array_push($ins,$arreglar[$j]['valor']);
                                    $nomb = $arreglar[$j]['NomNOP'];
                }
            }

            $valores[$i]['IDNOP'] = $ids[$i];
           $valores[$i]['NomNOP'] = $nomb;
            $valores[$i]['valores'] = $ins;
        }

//        print_r($valores);
        $consulta2 = $em->createQuery($dql);
        $consulta2->setParameter('idn', $idn);

        $confiltro =$consulta2-> getArrayResult();
//        print_r($confiltro );
        if($filter != ''){
            $ids = array();
            for($i = 0; $i < count($confiltro); $i++){
                if(!in_array($confiltro[$i]['IDNOP'],$ids)){
                    array_push($ids,$confiltro[$i]['IDNOP']);
                }
            }
//        print_r($ids);
            $valores = array();
            for($i = 0; $i < count($ids); $i++){
                $ins = array();
                $nomb = "";
                for($j = 0; $j < count($confiltro); $j++){
                    if($confiltro[$j]['IDNOP'] == $ids[$i]){
                        array_push($ins,$confiltro[$j]['valor']);
                        $nomb = $confiltro[$j]['NomNOP'];
                    }
                }
                if(strpos(strtolower($nomb), strtolower($filter)) !== false){
                    $valores[$i]['IDNOP'] = $ids[$i];
                    $valores[$i]['valores'] = $ins;
                    $valores[$i]['NomNOP'] = $nomb;
                }
            }
        }
if($cantCampos > 0){
    $respuesta['valores'] = $valores;
    $respuesta['count'] = count($consulta2->getArrayResult())/$cantCampos;
    return $respuesta;
}else{

    $respuesta['valores'] = array();
    $respuesta['count']  = 0;
    return $respuesta;
}

    }

    public function findByMostrarValoresCamposNomOp2($idn)
    {
        $em = $this->getEntityManager();

        $dql = 'SELECT nop.id as IDNOP,nop.nombre as NomNOP, cn.nombre as nombrecampo, vn.id, vn.valor
                  FROM EyCBundle:ValoresNom vn
                  JOIN vn.campoNom cn
                  JOIN vn.nomencladorOp nop
                  JOIN nop.nomenclador no
                 WHERE no.id = :idn';
//        AND vn.valor LIKE \'%'.$filter.'%\'
        $respuesta = array();
        $consulta = $em->createQuery($dql);
        $consulta->setParameter('idn', $idn);

        $arreglar = $consulta->getArrayResult();
        $ids = array();
        for($i = 0; $i < count($arreglar); $i++){
            if(!in_array($arreglar[$i]['IDNOP'],$ids)){
                array_push($ids,$arreglar[$i]['IDNOP']);
            }
        }
//        print_r($ids);
//        exit();
        $valores = array();
        for($i = 0; $i < count($ids); $i++){
            $ins = array();
            $nom = '';
            for($j = 0; $j < count($arreglar); $j++){
                if($arreglar[$j]['IDNOP'] == $ids[$i]){
                    array_push($ins,$arreglar[$j]['valor']);
                    $nom = $arreglar[$j]['NomNOP'];
                }
            }
            $valores[$i]['IDNOP'] = $ids[$i];
            $valores[$i]['NomNOP'] = $nom;
            $valores[$i]['valores'] = $ins;
        }

        $respuesta['valores'] = $valores;
        return $respuesta;
    }

    public function buscarNomOp($idn,$criterio)
    {
        $em = $this->getEntityManager();

        $dql = 'SELECT nop.nombre as nombreNOP ,cn.nombre as nombrecampo,vn.id, vn.valor
                  FROM EyCBundle:ValoresNom vn
                  JOIN vn.campoNom cn
                  JOIN vn.nomencladorOp nop
                  JOIN nop.nomenclador no
                 WHERE no.id = :idn
                   AND nop.nombre like :nombre';

        $consulta = $em->createQuery($dql);
        $consulta->setParameter('idn', $idn);
        $consulta->setParameter('nombre', '%' . $criterio . '%');

        return $consulta->getArrayResult();
    }
}
