<?php

namespace UCI\Boson\EyCBundle\Entity;

use Doctrine\ORM\EntityRepository;
use UCI\Boson\EyCBundle\Entity\Nomenclador;
use Doctrine\ORM\NoResultException;

/**
 * NomencladorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomencladorRepository extends EntityRepository
{

	
}
