<?php

namespace UCI\Boson\EyCBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ValoresEstrucRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValoresEstrucRepository extends EntityRepository
{
    public function valoresEstruc($id){

        $em = $this->getManager();

        $qb = $em->createQuery('SELECT v, c
		                          FROM EyCBundle:ValoresEstruc v
		                          JOIN v.campoEstruc c
		                         WHERE v.estructuraOp =: id');
        $qb->setParameter('id', $id);
        $valores = $qb->getResult();

        return $valores;
    }

}
