<?php

namespace UCI\Boson\EyCBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ValoresNomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValoresNomRepository extends EntityRepository
{
    public function findvaloresNom($id){


/*
        $qb = $em->createQuery("SELECT v, c
		                          FROM EyCBundle:ValoresNom v
		                          JOIN v.campoNom c
		                         WHERE v.nomencladorOp =: id");
        $qb->setParameter('id', $id);
        $valores = $qb->getResult();
*/
        $qb = $this->getEntityManager()->createQuery('SELECT v
		                          FROM EyCBundle:ValoresNom v
		                         WHERE v.nomencladorOp = :id');
        $qb->setParameter('id', $id);
        $valores = $qb->getResult();


        //$valores  = $this->getEntityManager()->getRepository('EyCBundle:ValoresNom')->find($id);


        return  $valores;
    }

}
